Models/ErrorViewModel.cs
namespace EstudoMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/UserModel.cs
namespace EstudoMVC.Models;

public class UserModel
{
    public string Nome { get; set; }
    public string Email { get; set; }
    public string Senha { get; set; }
}

Controllers/CadastroController.cs
using System.Diagnostics;
using EstudoMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace EstudoMVC.Controllers;

public class CadastroController : Controller
{
    private readonly ILogger<CadastroController> _logger;

    public CadastroController(ILogger<CadastroController> logger)
    {
        _logger = logger;
    }

    public IActionResult Cadastro()
    {
        return View();
    }

    public string Cadastrar([FromForm] UserModel userRequest) //criando formulário
    {
        return $"Nome: {userRequest.Nome}, Email: {userRequest.Email} e Senha: {userRequest.Senha}";
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/CalculadoraController.cs
using System.Diagnostics; // para Activity no final dessa classe
using EstudoMVC.Models; // para o erro de null no final
using Microsoft.AspNetCore.Mvc; // para o Controller

namespace EstudoMVC.Controllers; // nomeando

public class CalculadoraController : Controller
{
    private readonly ILogger<CalculadoraController> _logger;

    public CalculadoraController(ILogger<CalculadoraController> logger)
    {
        _logger = logger;
    }

    public IActionResult Calculadora() // apresentando a view
    {
        return View();
    }

    public IActionResult Calcular([FromForm] double num1, [FromForm] double num2, [FromForm] string operacao)
    {
        //operacao.ToLower();
        if(operacao == "soma")
        {
            ViewBag.Operacao = operacao;
            ViewBag.Numero1 = num1;
            ViewBag.Numero2 = num2;
            ViewBag.Resultado = num1 + num2;
            return View("ResultadoCalculadora");
        }
        if(operacao == "subtrair")
        {
            ViewBag.Operacao = operacao;
            ViewBag.Numero1 = num1;
            ViewBag.Numero2 = num2;
            ViewBag.Resultado = num1 - num2;
            return View("ResultadoCalculadora");
        }
        if(operacao == "multiplicar")
        {
            ViewBag.Operacao = operacao;
            ViewBag.Numero1 = num1;
            ViewBag.Numero2 = num2;
            ViewBag.Resultado = num1 * num2;
            return View("ResultadoCalculadora");
        }
        if(operacao == "dividir")
        {
            ViewBag.Operacao = operacao;
            ViewBag.Numero1 = num1;
            ViewBag.Numero2 = num2;
            ViewBag.Resultado = num1 / num2;
            return View("ResultadoCalculadora");
        }
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using EstudoMVC.Models;

namespace EstudoMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/OperacoesMatematicasController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using EstudoMVC.Models;

namespace EstudoMVC.Controllers;

public class OperacoesMatematicasController : Controller {

    private readonly ILogger<OperacoesMatematicasController> _logger;

    public OperacoesMatematicasController(ILogger<OperacoesMatematicasController> logger)
    {
        _logger = logger;
    }

    public IActionResult Somar()
    {
        return View();
    }

    public IActionResult Subtrair()
    {
        return View();
    }

    public IActionResult Multiplicar()
    {
        return View();
    }

    public IActionResult Dividir()
    {
        return View();
    }

    public IActionResult OperacaoSomar([FromForm] double num1, [FromForm] double num2)
    {
        ViewBag.Operacao = "Soma";
        ViewBag.Numero1 = num1;
        ViewBag.Numero2 = num2;
        ViewBag.Resultado = num1 + num2;
        return View("ResultadoOperacoes");
    }

    public IActionResult OperacaoSubtrair([FromForm] double num1, [FromForm] double num2)
    {
        ViewBag.Operacao = "Subtração";
        ViewBag.Numero1 = num1;
        ViewBag.Numero2 = num2;
        ViewBag.Resultado = num1 - num2;
        return View("ResultadoOperacoes");
    }

    public IActionResult OperacaoMultiplicar([FromForm] double num1, [FromForm] double num2)
    {
        ViewBag.Operacao = "Multiplicação";
        ViewBag.Numero1 = num1;
        ViewBag.Numero2 = num2;
        ViewBag.Resultado = num1 * num2;
        return View("ResultadoOperacoes");
    }

    public IActionResult OperacaoDividir([FromForm] double num1, [FromForm] double num2)
    {
        ViewBag.Operacao = "Divisão";
        ViewBag.Numero1 = num1;
        ViewBag.Numero2 = num2;
        ViewBag.Resultado = num1 / num2;
        return View("ResultadoOperacoes");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Cadastro/Cadastro.cshtml
@{
    ViewData["Title"] = "Cadastro";
}

<div class="text-center">
    <h1>Cadastro</h1>
    <form action="Cadastrar" method="post">
        <p>
            <label for="nome">Nome</label>
            <input type="text" id="nome" name="nome">
            <label for="email">Email</label>
            <input type="email" name="email" id="email">
        </p>
        <p>
            <label for="senha">Senha</label>
            <input type="password" name="senha" id="senha">
        </p>
        <input type="submit" value="Enviar">
    </form>
</div>

Views/Calculadora/Calculadora.cshtml
@{
    ViewData["Title"] = "Calculadora";
}

<div class="text-center">
    <h1>Calculadora</h1>
    <form action="Calcular" method="post">
        <p>
            <label for="num1">Número 1:</label>
            <input type="number" id="num1" name="num1">
            <label for="num2">Número 2:</label>
            <input type="number" name="num2" id="num2">
        </p>
        <p>
            <label for="operacao">Operação:</label>
            <select name="operacao" id="operacao">
                <option selected value="soma">Soma</option>
                <option value="multiplicar">Multiplicação</option>
                <option value="dividir">Divisão</option>
                <option value="subtrair">Subtração</option>
            </select>
        </p>
        <input type="submit" value="Enviar">
    </form>
</div>

Views/Calculadora/ResultadoCalculadora.cshtml
@{
    ViewData["Title"] = "Resultado";
}

<div class="text-center">
    <h1>Resultado da @ViewBag.Operacao</h1>
    <p>
        A @ViewBag.Operacao do número @ViewBag.Numero1 com @ViewBag.Numero2 será @ViewBag.Resultado
    </p>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/OperacoesMatematicas/Dividir.cshtml
@{
    ViewData["Title"] = "Dividir";
}

<div class="text-center">
    <h1>Divisão</h1>
    <form action="OperacaoDividir" method="post">
        <p>
            <label for="num1">Número 1:</label>
            <input type="number" id="num1" name="num1">
            <label for="num2">Número 2:</label>
            <input type="number" name="num2" id="num2">
        </p>
        <input type="submit" value="Enviar">
    </form>
</div>

Views/OperacoesMatematicas/Multiplicar.cshtml
@{
    ViewData["Title"] = "Multiplicar";
}

<div class="text-center">
    <h1>Multiplicação</h1>
    <form action="OperacaoMultiplicar" method="post">
        <p>
            <label for="num1">Número 1:</label>
            <input type="number" id="num1" name="num1">
            <label for="num2">Número 2:</label>
            <input type="number" name="num2" id="num2">
        </p>
        <input type="submit" value="Enviar">
    </form>
</div>

Views/OperacoesMatematicas/ResultadoOperacoes.cshtml
@{
    ViewData["Title"] = "Resultado";
}

<div class="text-center">
    <h1>Resultado da @ViewBag.Operacao</h1>
    <p>
        A @ViewBag.Operacao do número @ViewBag.Numero1 com @ViewBag.Numero2 será @ViewBag.Resultado
    </p>
</div>

Views/OperacoesMatematicas/Somar.cshtml
@{
    ViewData["Title"] = "Somar";
}

<div class="text-center">
    <h1>Soma</h1>
    <form action="OperacaoSomar" method="post">
        <p>
            <label for="num1">Número 1:</label>
            <input type="number" id="num1" name="num1">
            <label for="num2">Número 2:</label>
            <input type="number" name="num2" id="num2">
        </p>
        <input type="submit" value="Enviar">
    </form>
</div>

Views/OperacoesMatematicas/Subtrair.cshtml
@{
    ViewData["Title"] = "Subtrair";
}

<div class="text-center">
    <h1>Subtração</h1>
    <form action="OperacaoSubtrair" method="post">
        <p>
            <label for="num1">Número 1:</label>
            <input type="number" id="num1" name="num1">
            <label for="num2">Número 2:</label>
            <input type="number" name="num2" id="num2">
        </p>
        <input type="submit" value="Enviar">
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EstudoMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EstudoMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EstudoMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OperacoesMatematicas" asp-action="Somar">Somar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OperacoesMatematicas" asp-action="Subtrair">Subtrair</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OperacoesMatematicas" asp-action="Multiplicar">Multiplicar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OperacoesMatematicas" asp-action="Dividir">Dividir</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculadora" asp-action="Calculadora">Calculadora</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cadastro" asp-action="Cadastro">Cadastro</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EstudoMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>